package com.example.ubapplicationsample1;


import java.util.Random;


public class items {

	public String name; 
	public String iconUrl;
	public String availability;
	public String tier;
	public String stats;
	public String passive1;
	public String passive2;
	public String passive3;
	public String passive4;
	public String passive5;
	public String menu;
	public String itemCost;
	public String sellValue;
	public static items[] itemsArray = new items[100];
	
	
	//Method to get random boots. High must be 1 higher than the desired index
	//VALID INDEXES ARE 0 TO 6
	public static int getBoots(){
		Random r = new Random();
		int Low = 0;
		int High = 7;
		int R = r.nextInt(High-Low) + Low;
		return R;
	}
	
	//Method to get random items (not boots). High must be 1 higher than desired index
	//VALID INDEXES ARE 7 TO 67
	public static int getItems(){
		Random r = new Random();
		int Low = 7;
		int High = 68;
		int R = r.nextInt(High-Low) + Low;
		return R;
		
	}
	
	//Constructor
	public items(String a, String b, String c, String d, String e, String f, String g, String h, String i, String j, String k, String l, String m){
		name = a;
		iconUrl = b;
		availability = c;
		tier = d;
		stats = e;
		passive1 = f;
		passive2 = g;
		passive3 = h;
		passive4 = i;
		passive5 = j;
		menu = k;
		itemCost = l;
		sellValue = m;
	}
	
	//Methods to return Strings for items
	public static String getName(items a){
		return a.name;
	}
	public static String getIconUrl(items a){
		return a.iconUrl;
	}
	public static String getAvailability(items a){
		return a.availability;
	}
	public static String getTier(items a){
		return a.tier;
	}
	public static String getStats(items a){
		return a.stats;
	}
	public static String getPassive1(items a){
		return a.passive1;
	}
	public static String getPassive2(items a){
		return a.passive2;
	}
	public static String getPassive3(items a){
		return a.passive3;
	}
	public static String getPassive4(items a){
		return a.passive4;
	}
	public static String getPassive5(items a){
		return a.passive5;
	}
	public static String getMenu(items a){
		return a.menu;
	}
	public static String getItemCost(items a){
		return a.itemCost;
	}
	public static String getSellValue(items a){
		return a.sellValue;
	}

	
	public static void runMain(){
		itemsArray[0] = new items("Ionian Boots of Lucidity", "http://img1.wikia.nocookie.net/__cb20130319090448/leagueoflegends/images/1/14/Ionian_Boots_of_Lucidity_item.png", "Common", "Advanced", null, "Unique: +15% cooldown reduction", "Unique - Enhanced Movement: +45 movement speed", null, null, null, "Magic > Cooldown Reduction \nMovement", "1000g (675g)", "700g");
		itemsArray[1] = new items("Berserker's Greaves", "http://img4.wikia.nocookie.net/__cb20130116005955/leagueoflegends/images/b/bd/Berserker%27s_Greaves_item.png", "Common", "Advanced", "+20% atttack speed", "Unique - Enhanced Movement: +45 movement speed", null, null, null, null, "Attack > Attack Speed \nMovement", "900g (175g)", "630g");
		itemsArray[2] = new items("Boots of Mobility", "http://img2.wikia.nocookie.net/__cb20130319090211/leagueoflegends/images/9/90/Boots_of_Mobility_item.png", "Common", "Advanced", null, "Unique - Enhanced Movement: +25 movement speed. Increases to +105 movement speed when out of combat for 5 seconds.", null, null, null, null, "Movement", "800g (475g)", "560g");
		itemsArray[3] = new items("Boots of Swiftness", "http://img2.wikia.nocookie.net/__cb20130319090224/leagueoflegends/images/6/69/Boots_of_Swiftness_item.png", "Common", "Advanced", null, "Unique - Enhanced Movement: +60 movement speed.", "Unique - Slow Resist: Movement slowing effects are reduced by 25%", null, null, null, "Movement", "1000g (675g)", "700g");
		itemsArray[4] = new items("Mercury's Treads", "http://img1.wikia.nocookie.net/__cb20130319090758/leagueoflegends/images/9/96/Mercury%27s_Treads_item.png", "Common", "Advanced", "+25 magic resistance", "Unique - Enhanced Movement: +45 movement speed", "Unique - Tenacity: the duration of stuns, slows, taunts, fears, silences, blinds, and immobilizes are reduced by 35%.", null, null, null, "Defense > Magic Resist \nMovement", "1200g (475g)", "840g");
		itemsArray[5] = new items("Ninja Tabi", "http://img2.wikia.nocookie.net/__cb20130319091031/leagueoflegends/images/3/35/Ninja_Tabi_item.png", "Common", "Advanced", "+25 armor", "Unique - Enhanced Movement: +45 movement speed.", "Unique: Blocks 10% of the damage from basic attacks.", null, null, null, "Defense > Armor \nMovement", "1000g (375g)", "700g");
		itemsArray[6] = new items("Sorcerer's Shoes", "http://img2.wikia.nocookie.net/__cb20130319091505/leagueoflegends/images/6/60/Sorcerer%27s_Shoes_item.png", "Common", "Advanced", "+15 magic penetration", "Unique - Enhanced Movement: +45 movement speed.", null, null, null, null, "Movement", "1100g (775g)", "770g");
		itemsArray[7] = new items("Guardian Angel", "http://img1.wikia.nocookie.net/__cb20130319090348/leagueoflegends/images/f/f4/Guardian_Angel_item.png", "Summoner's Rift \nCrystal Scar", "Advanced", "+50 armor \n+40 magic resistance", "Unique: Revives your champion upon death, restoring 30$ of your maximum health and mana after 4 seconds of stasis. 5 minute cooldown.", null, null, null, null, "Defense > Armor \nDefense > Magic Resist", "2750g (1310g)", "1100g");
		itemsArray[8] = new items("Infinity Edge", "http://img2.wikia.nocookie.net/__cb20130319090446/leagueoflegends/images/1/15/Infinity_Edge_item.png", "Summoner's Rift", "Advanced", "+70 attack damage \n+25% critical strike chance", "Unique: +50% critical strike damage", null, null, null, null, "Attack > Critical Strike \nAttack > Damage", "3800g (645g)", "2660g");
		itemsArray[9] = new items("Mejai's Soulstealer", "http://img3.wikia.nocookie.net/__cb20130319090740/leagueoflegends/images/2/2e/Mejai%27s_Soulstealer_item.png", "Summoner's Rift", "Advanced", "+20 ability power", "Unique: Grants +8 ability power per stack. Gains 2 stacks for a kill or 1 stack for an assist (max 20 stacks). A third of the current stacks are lost upon death. At 20 stacks, grants 15% cooldown reduction.", null, null, null, null, "Magic > Ability Power", "1235g (800g)", "865g");
		itemsArray[10] = new items("Rabadon's Deathcap", "http://img4.wikia.nocookie.net/__cb20130319091242/leagueoflegends/images/c/c5/Rabadon%27s_Deathcap_item.png", "Summoner's Rift \nHowling Abyss", "Advanced", "+120 ability power", "Unique: +30% ability power", null, null, null, null, "Magic > Ability Power", "3300g (840g)", "2310g");
		itemsArray[11] = new items("Sword of the Occult", "http://img1.wikia.nocookie.net/__cb20130319091544/leagueoflegends/images/3/33/Sword_of_the_Occult_item.png", "Summoner's Rift", "Advanced", "+10 attack damage", "Unique: Grants +5 attack damage per stack. Gains 2 stacks for a kill or 1 stack for an assist (max 20 stacks). A third of the current stacks are lost upon death. At 20 stacks, grants 15% bonus movement speed.", null, null, null, null, "Attack > Damage", "1200g (840g)", "840g");
		itemsArray[12] = new items("Thornmail", "http://img2.wikia.nocookie.net/__cb20130731234542/leagueoflegends/images/4/4f/Thornmail_item.png", "Summoner's Rift \nCrystal Scar \nHowling Abyss", "Advanced", "+100 armor", "Unique: On being hit by basic attacks, returns 30% of damage, before any reductions such as armor, as magic damage.", null, null, null, null, "Defense > Armor", "2200g (1180g)", "1540g");
		itemsArray[13] = new items("Warmog's Armor", "http://img3.wikia.nocookie.net/__cb20130319091642/leagueoflegends/images/9/9f/Warmog%27s_Armor_item.png", "Summoner's Rift", "Advanced", "+1000 health", "Unique Passive: You gain health regeneration equal to 1% of your maximum health.", null, null, null, null, "Defense > Health \nDefense > Health Regen", "2830g (1070g)", "1981g");
		itemsArray[14] = new items("Abyssal Scepter", "http://img4.wikia.nocookie.net/__cb20130731234819/leagueoflegends/images/2/2b/Abyssal_Scepter_item.png", "Common", "Advanced", "+70 ability power \n+45 magic resistance", "Unique: Reduces the magic resist of nearby enemies by 20 (700 range).", null, null, null, null, "Defense > Magic Resist \nMagic > Ability Power", "2560g (980g)", "1792g");
		itemsArray[15] = new items("Frozen Mallet", "http://img2.wikia.nocookie.net/__cb20130319090339/leagueoflegends/images/a/ac/Frozen_Mallet_item.png", "Common", "Advanced", "+700 health \n+30 attack damage", "Unique - Icy: Your basic attacks slow your target's Movement Speed by 40% for 1.5 seconds (30% slow for ranged attacks)", null, null, null, null, "Attack > Damage \nDefense > Health", "3300g (1025g)", "2310g");
		itemsArray[16] = new items("Guinsoo's Rageblade", "http://img1.wikia.nocookie.net/__cb20130319090419/leagueoflegends/images/9/95/Guinsoo%27s_Rageblade_item.png", "Common", "Advanced", "+40 ability power \n+30 attack damage", "Passive: Autoattacks (on attack) and champion abilities grant +4% attack speed and +4 ability power for 8 seconds (stacks up to 8 times).", "Unique Passive: Falling below 50% health grants +20% attack speed, +10% life steal, and 10% spell vamp until out of combat. 30 second cooldown.", null, null, null, "Attack > Damage \nAttack > Attack Speed \nMagic > Ability Power", "2600g (865g)", "1820g");
		itemsArray[17] = new items("Last Whisper", "http://img4.wikia.nocookie.net/__cb20130319090547/leagueoflegends/images/b/ba/Last_Whisper_item.png", "Common", "Advanced", "+40 attack damage", "Unique: +35% armor penetration", null, null, null, null, "Attack > Damage", "2300g (1065g)", "1610g");
		itemsArray[18] = new items("Runaan's Hurricane", "http://img4.wikia.nocookie.net/__cb20130710101718/leagueoflegends/images/f/f5/Runaan%27s_Hurricane_item.png", "Common", "Advanced", "+70% attack speed", "Ranged only: Unique Passive: your basic attacks fire minor bolts at 2 nearby targets, each dealing 10 (+50% AD) physical damage and applying on-hit effects.", null, null, null, null, "Attack > Attack Speed", "2400g (700g)", "1680g");
		itemsArray[19] = new items("Rylai's Crystal Scepter", "http://img4.wikia.nocookie.net/__cb20130319091435/leagueoflegends/images/f/f2/Rylai%27s_Crystal_Scepter_item.png", "Common", "Advanced", "+80 ability power \n+500 health", "Unique: Dealing spell damage slows the target's movement speed by 35% for 1.5 seconds (15% for multi-target and damage-over-time spells).", null, null, null, null, "Defense > Health \nMagic > Ability Power", "2900g (605g)", "2030g");
		itemsArray[20] = new items("Sunfire Cape", "http://img2.wikia.nocookie.net/__cb20131123181503/leagueoflegends/images/6/61/Sunfire_Cape_item.png", "Common", "Advanced", "+450 health \n+45 armor", "Unique passive: Deals 25 + (1 x level) magic damage per second to nearby enemies (400 range).", null, null, null, null, "Defense > Armor \nDefense > Health", "2650g (930g)", "1855g");
		itemsArray[21] = new items("Sword of the Divine", "http://img2.wikia.nocookie.net/__cb20130319094452/leagueoflegends/images/9/9c/Sword_of_the_Divine_item.png", "Common", "Advanced", "+45% attack speed", "Passive: This item does not grant any attack speed while on cooldown. Champion kills redue the current cooldown by 50%.", "Unique Active: You gain 100% attack speed and 100% critical strike chance for 3 seconds or 3 critical strikes. 60 second cooldown", null, null, null, "Attack > Attack Speed \nAttack > Critical Strike", "2150g (850g)", "1505g");
		itemsArray[22] = new items("Void Staff", "http://img1.wikia.nocookie.net/__cb20130319091635/leagueoflegends/images/6/65/Void_Staff_item.png", "Common", "Advanced", "+70 ability power", "Unique: +35% magic penetration", null, null, null, null, "Magic > Ability Power", "2295g (1000g)", "1607g");
		itemsArray[23] = new items("Wit's End", "http://img3.wikia.nocookie.net/__cb20130319091648/leagueoflegends/images/1/16/Wit%27s_End_item.png", "Common", "Advanced", "+42% attack speed \n+25 magic resistance", "Unique: Basic attacks deal 42 bonus magic damage on hit.", "Unique: Basic attacks increase your magic resistance by 5 for 5 seconds and reduce the target's magic resistance by 5 on hit (stacks up to 5 times).", null, null, null, "Attack > Attack Speed \nDefense > Magic Resist", "2400g (700g)", "1680g");
		itemsArray[24] = new items("Banshee's Veil", "http://img1.wikia.nocookie.net/__cb20130319090152/leagueoflegends/images/0/03/Banshee%27s_Veil_item.png", "Summoner's Rift \nTwisted Treeline \nHowling Abyss", "Legendary", "+450 health \n+55 magic resistance", "Unique: Grants a spell shield that blocks the next enemy ability. This shield refreshes after no damage is taken from enemy champions for 25 seconds.", "Unique: Grants 45 health regen for up to 10 seconds after taking damage from an enemy champion or when the spell shield breaks.", null, null, null, "Defense > Health \nDefense > Magic Resist", "2750g (950g)", "1925g");
		itemsArray[25] = new items("Deathfire Grasp", "http://img2.wikia.nocookie.net/__cb20130731230043/leagueoflegends/images/a/a8/Deathfire_Grasp_item.png", "Summoner's Rift \nHowling Abyss", "Legendary", "+120 ability power \n+10% cooldown reduction", "Unique Active: Deals 15% of target champion's maximum health in magic damage and applies the debuff, Doom. Doom amplifies all magic damage that champion takes by 20% for 4 seconds. 60 second cooldown (750 range).", null, null, null, null, "Magic > Ability Power \nMagic > Cooldown Reduction", "3100g (680g)", "2170g");
		itemsArray[26] = new items("The Bloodthrister", "http://img1.wikia.nocookie.net/__cb20130319091558/leagueoflegends/images/7/72/The_Bloodthirster_item.png", "Summoner's Rift", "Legendary", "+70 attack damage \n+12% life steal", "Grants +1 attack damage and +0.2% life steal per stack (max +30 attack damage and +6% life steal). Half of the current stacks are lost upon death.", null, null, null, null, "Attack > Damage \nAttack > Life Steal", "3200g (850g)", "2240g");
		itemsArray[27] = new items("Mercurial Scimitar", "http://img3.wikia.nocookie.net/__cb20130710102449/leagueoflegends/images/0/0a/Mercurial_Scimitar_item.png", "Summoner's Rift \nHowling Abyss", "Legendary", "+60 attack damage \n+45 magic resistance", "Unique Active - Quicksilver: Removes all debuffs from your champion. Melee champions also gain +50% movement speed for 1 second. 90 second cooldown.", null, null, null, null, "Defense > Magic Resist \nAttack > Attack Damage \nMovement > Other Movement Items", "3700g (600g)", "2590g");
		itemsArray[28] = new items("Ohmwrecker", "http://img2.wikia.nocookie.net/__cb20130710102757/leagueoflegends/images/6/6c/Ohmwrecker_item.png", "Summoner's Rift \nTwisted Treeline", "Advanced", "+350 health \n+50 ability power", "Unique Active: Prevents the closest enemy tower from attack for 2.5 seconds (120 second cooldown). This effect cannot be used against the same tower more than once every 7.5 seconds.", null, null, null, null, "Defense > Health \nMagic > Ability Power", "2000g (740g)", "1400g");
		itemsArray[29] = new items("Ruby Sightstone", "http://img1.wikia.nocookie.net/__cb20130710102450/leagueoflegends/images/5/5d/Ruby_Sightstone_item.png", "Summoner's Rift", "Consumable \nLegendary", "+400 health", "Unique Passive: Ward Refresh - Holds 5 charges and refills upon visiting the shop.", "Unique Active: Ghost Ward - Consumes a charge to place a Stealth Ward that reveals the surrounding area for 3 minutes. A player may only have 3 Stealth Wards on the map at one time.", null, null, null, "Defense > Health \nConsumable", "1600g (400g)", "620g");
		itemsArray[30] = new items("Spirit of the Ancient Golem", "http://img1.wikia.nocookie.net/__cb20130710102449/leagueoflegends/images/9/93/Spirit_of_the_Ancient_Golem_item.png", "Summoner's Rift \nTwisted Treeline \nHowling Abyss", "Legendary", "+350 health \n+10% cooldown reduction", "Unique Passive - Tenacity: The duration of stuns, slows, taunts, fears, silences, blinds, polymorphs, and immobilizes are reduced by 35%.", "Unique Passive - Butcher: Against monsters, deal 30% bonus damage and restore 6% of damage dealt to monsters as health and 3% as mana.", "Unique Passive - Conservation: You generate Conservation stacks every 1.5 seconds up to 80. Killing a large monster will consume up to 40 stacks and grant 1 bonus gold per stack consumed. You may only be in possession of 1 Gold Income item.", null, null, "Gold Income \nDefense > Health \nMagic > Cooldown Reduction", "2000g (450g)", "800g");
		itemsArray[31] = new items("Spirit of the Elder Lizard", "http://img3.wikia.nocookie.net/__cb20130710102448/leagueoflegends/images/f/fa/Spirit_of_the_Elder_Lizard_item.png", "Summoner's Rift \nTwisted Treeline \nHowling Abyss", "Legendary", "+30 attack damage \n+10% cooldown reduction", "Unique Passive - Incinerate: Deals and additional 14 + (2 x level) bonus true damage over 3 seconds upon dealing physical damage.", "Unique Passive - Butcher: Against monsters, deal 20% bonus damage and restore 6% of damage dealt to monsters as health and 3% as mana.", "Unique Passive - Conservation: You generate Conservation stacks every 1.5 seconds up to 80. Killing a large monster will consume up to 40 stacks and grant 1 bonus gold per stack consumed. You may only be in possession of 1 Gold Income item.", null, null, "Gold Income \nDefense > Health Regen \nAttack > Damage \nMagic > Mana Regen", "2000g (580g)", "800g");
		itemsArray[32] = new items("Spirit of the Spectral Wraith", "http://img4.wikia.nocookie.net/__cb20130710102448/leagueoflegends/images/2/2b/Spirit_of_the_Spectral_Wraith_item.png", "Summoner's Rift \nTwisted Treeline \nHowling Abyss", "Legendary", "+50 ability power \n+10% cooldown reduction", "Unique Passive - Spirit Drain: Grants 2 ability power for every large monster kill (max: 15 stacks)", "Unique Passive - Butcher: Against monsters, deal 30% bonus damage and restore 6% of damage dealt to monsters as health and 3% as mana.", "Unique Passive - Conservation: You generate Conservation stacks every 1.5 seconds up to 80. Killing a large monster will consume up to 40 stacks and grant 1 bonus gold per stack consumed. You may only be in possession of 1 Gold Income item.", null, null, "Gold Income \nMagic > Ability Power \nMagic > Cooldown Reduction", "2000g (480g)", "800g");
		itemsArray[33] = new items("Zhonya's Hourglass", "http://img3.wikia.nocookie.net/__cb20130319091852/leagueoflegends/images/b/b5/Zhonya%27s_Hourglass_item.png", "Summoner's Rift \nHowling Abyss", "Legendary", "+120 ability power \n+50 armor", "Unique Active - Statis: Champion becomes invulnerable and untargetable for 2.5 seconds, but is unable to move, attack, cast spells, or use items during this time (90 second cooldown).", null, null, null, null, "Magic > Abilty Power \nDefense > Armor", "3260g (500g)", "2282g");
		itemsArray[34] = new items("Athene's Unholy Grail", "http://img3.wikia.nocookie.net/__cb20130111231157/leagueoflegends/images/c/cc/Athene%27s_Unholy_Grail_item.png", "Common", "Legendary", "+60 ability power \n+40 magic resistance \n+15 mana regeneration \n+20% cooldown reduction", "Unique Passive - Mana Font: Increases your mana regeneration by 1% per 1% mana you are missing.", "Unique Passive: Restores 12% of your max mana on kill or assist", null, null, null, "Defense > Magic Resist \nMagic < Ability Power \nMagic > Mana Regen \nMagic > Cooldown Reduction", "2600g (900g)", "1820g");
		itemsArray[35] = new items("Atma's Impaler", "http://img2.wikia.nocookie.net/__cb20130319090010/leagueoflegends/images/3/3b/Atma%27s_Impaler_item.png", "Common", "Legendary", "+45 armor \n+15% critical strike chance", "Unique Passive: You gain attack damage equal to 1.5% of your maximum health.", null, null, null, null, "Attack > Attack Damage \nAttack > Critical Strike \nDefense > Armor", "2300g (780g)", "1610g");
		itemsArray[36] = new items("Banner of Command", "http://img3.wikia.nocookie.net/__cb20130710101720/leagueoflegends/images/9/9e/Banner_of_Command_item.png", "Common", "Legendary", "+80 ability power \n+20% cooldown reduction", "Unique Aura - Valor: Nearby allied minions have 15% increased attack damage and ability power.", "Unique Active - Promote: Transforms a nearby siege minion to a more powerful unit. You gain all the gold this unit earns. 180 second cooldown.", null, null, null, "Magic > Ability Power \nMagic > Cooldown Reduction", "2400g (720g)", "1680g");
		itemsArray[37] = new items("The Black Cleaver", "http://img2.wikia.nocookie.net/__cb20130319091555/leagueoflegends/images/9/98/The_Black_Cleaver_item.png", "Common", "Legendary", "+200 health \n+50 attack damage \n+10% cooldown reduction \nUNIQUE: +10 armor penetration", "Passive: Dealing physical damage to an enemy champion reduces their armor by 5% for 4 seconds. This effect stacks up to 5 times.", null, null, null, null, "Attack > Damage \nMagic > Cooldown Reduction \nDefense > Health", "3000g (1263g)", "2100g");
		itemsArray[38] = new items("Talisman of Ascension", "http://img2.wikia.nocookie.net/__cb20131112145246/leagueoflegends/images/3/32/Talisman_of_Ascension_item.png", "Common", "Legendary", "+20% cooldown reduction \n+10 health regeneration \n+15 mana regeneration \n+2 gold per 10 seconds", "Unique Passive - Favor: Being near a minion death without granting the killing blow grants 3 gold and heals for 10 health. You may only be in possession of 1 Gold Income item.", "Unique Active: Grants nearby allies +40% movement speed for 3 seconds. 60 second cooldown. (600 range)", null, null, null, "Gold Income \nDefense > Health Regen \nMagic > Cooldown Reduction \nMagic > Mana Regen \nMovement > Other Movement Items", "2200g (585g)", "880g");
		itemsArray[39] = new items("Trinity Force", "http://img2.wikia.nocookie.net/__cb20130319091621/leagueoflegends/images/3/3d/Trinity_Force_item.png", "Common", "Legendary", "+30 ability power \n+30 attack damage \n+30% attack speed \n+10% critical strike chance \n+250 health \n+200 mana \n+8% movement speed", "Unique Passive - Rage: Basic attacks grant 20 movement speed for 2 seconds on hit. Minion, monster, and champion kills grant 60 movement speed for 2 seconds. The movement speed bonus is halved for ranged champions.", "Unique Passive - Spellblade: After using an ability, your next basic attack deals 200% base AD bonus physical damage. (2 second cooldown).", null, null, null, "Attack > Attack Damage \nAttack > Attack Speed \nAttack > Critical Strike \nDefense > Health \nMagic > Ability Power \nMagic > Mana \nMovement > Other Movement Items", "3703g (3g)", "2592g");
		itemsArray[40] = new items("Executioner’s Calling", "http://img1.wikia.nocookie.net/__cb20130319090327/leagueoflegends/images/3/3d/Executioner%27s_Calling_item.png", "Common", "Legendary", "+25 attack damage \n+20% critical strike chance", "Unique: Your basic attacks inflict Grievous Wounds on enemy champion for 1.5 seconds.", null, null, null, null, "Attack > Critical Strike \nAttack > Damage", "1900g (740g)", "1330g");
		itemsArray[41] = new items("Face of the Mountain", "http://img3.wikia.nocookie.net/__cb20131117020510/leagueoflegends/images/e/e8/Face_of_the_Mountain_item.png", "Common", "Legendary", "+500 health \n+20 health regeneration \n+10% cooldown reduction", "Unique Passive – Spoils of War: Melee autoattacks execute minions below 200 (+100% AD) health. Killing a minion by any means heals yourself and the nearest allied champion for 50 (+1% of your maximum health) health and grants them gold equal to the kill. These effects require a nearby allied champion and consume a charge. Recharges every 30 seconds for a maximum of 4 charges. You may only be in possession of 1 Gold Income item.", "Unique Active – Deadly Phalanx: You shield the target ally for 10% of your maximum health for 4 seconds. After 4 seconds, the shield explodes, dealing magic damage equal to (100% of target’s AD) + (30% of target’s AP), regardless of if the shield remained intact. 60 second cooldown.", null, null, null, "Defense > Health \nDefense > Health Regen \nMagic > Cooldown Reduction", "2200g (485g)", "880g");
		itemsArray[42] = new items("Frost Queen’s Claim", "http://img2.wikia.nocookie.net/__cb20131116140853/leagueoflegends/images/7/77/Frost_Queen%27s_Claim_item.png", "Common", "Legendary", "+50 ability power \n+10% cooldown reduction \n+10mana regeneration \n +4 gold per 10 seconds", "Unique Passive – Tribute: Your next damaging ability or autoattack against a champion or structure will deal 15 additional damage and grant 10 gold. You generate one charge of Tribute every 10 seconds storing up to 3.", "Unique Active – Arctic Embrace: Fire an ice lance that detonates at the target location, dealing 50 (+5 per level) magic damage to enemies and slowing them by 80%, decaying over 2 seconds. 60 second cooldown. (850 range, 225 radius).", null, null, null, "Gold Income \nMagic > Ability Power \nMagic > Cooldown Reduction \nMagic > Mana Regen", "2200g (515g)", "880g");
		itemsArray[43] = new items("Frozen Heart", "http://img2.wikia.nocookie.net/__cb20130319090337/leagueoflegends/images/5/58/Frozen_Heart_item.png", "Common", "Legendary", "+100 armor \n+400 mana \n+20% cooldown reduction", "Unique: Reduces the attack speed of nearby enemies by 15%. (700 range).", null, null, null, null, "Defense > Armor \nMagic > Cooldown Reduction \nMagic > Mana", "2600g (650g)", "1820g");
		itemsArray[44] = new items("Iceborn Gauntlet", "http://img2.wikia.nocookie.net/__cb20130319090444/leagueoflegends/images/c/c4/Iceborn_Gauntlet_item.png", "Common", "Legendary", "+30 ability power \n+500 mana \n+60 armor \n+10% cooldown reduction", "Unique Passive – Spellblade: After using an ability, your next basic attack deals 125% base AD bonus physical damage to surrounding enemies and creates a field for 2 seconds that slows enemies inside by 30% (2 second cooldown).", null, null, null, null, "Defense > Armor \nMagic > Ability Power \nMagic > Cooldown Reduction \nMagic > Mana", "2900g (750g)", "2030g");
		itemsArray[45] = new items("Liandry’s Torment", "http://img1.wikia.nocookie.net/__cb20130710101719/leagueoflegends/images/f/fd/Liandry%27s_Torment_item.png", "Common", "Legendary", "+50 ability power \n+300 health", "Unique Passive – Eyes of Pain: +15 magic penetration", "Unique Passive: Dealing spell damage applies a damage-over-time effect that deals bonus magic damage equal to 2% of the target’s current Health per second for 3 seconds. This bonus is doubled against movement-impaired units and capped at 100 damage per second vs. monsters.", null, null, null, "Defense > Health \nMagic > Ability Power", "2900g (980g)", "2030g");
		itemsArray[46] = new items("Lich Bane", "http://img2.wikia.nocookie.net/__cb20130319090609/leagueoflegends/images/6/60/Lich_Bane_item.png", "Common", "Legendary", "+80 ability power \n+250 mana \n+5% movement speed", "Unique Passive – Spellblade: After using an ability, your next basic attack deals 75% base AD (+ 50% AP) bonus magic damage. 2 second cooldown.", null, null, null, null, "Magic >Ability Power \nMagic > Mana \nMovement > Other Movement Items", "3000g (940g)", "2100g");
		itemsArray[47] = new items("Locket of the Iron Solari", "http://img3.wikia.nocookie.net/__cb20130319090622/leagueoflegends/images/5/56/Locket_of_the_Iron_Solari_item.png", "Common", "Legendary", "+400 health \n+20 magic resistance \n+10% cooldown reduction", "Unique Aura – Legion: Nearby allied champions gain +20 magic resist and +10 health regen per 5 seconds. (1100 range).", "Unique Active: Shield yourself and nearby allied champions for 5 seconds, absorbing up to 50 (+10 per level) damage. 60 second cooldown. (600 range).", null, null, null, "Defense > Health \nDefense > Health Regen \nDefense > Magic Resist \nMagic > Cooldown Reduction", "2800g (50g)", "1960g");
		itemsArray[48] = new items("Maw of Malmortius", "http://img3.wikia.nocookie.net/__cb20130319090734/leagueoflegends/images/1/14/Maw_of_Malmortius_item.png", "Common", "Legendary", "+60 attack damage \n+40 magic resistance", "Unique: Grants +1 attack damage for every 2% of missing health, capped at 35 Attack Damage.", "Unique Passive – Lifeline: Upon taking magic damage that would reduce health below 30%, grants a shield that absorbs 400 magic damage for 5 seconds (90 second cooldown).", null, null, null, "Defense > Magic Resistance \nAttack > Damage", "3200g (975g)", "2310g");
		itemsArray[49] = new items("Mikael’s Crucible", "http://img1.wikia.nocookie.net/__cb20130710101718/leagueoflegends/images/d/de/Mikael%27s_Crucible_item.png", "Summoner’s Rift", "Legendary", "+40 magic resist \n+12 mana regeneration", "Unique Passive – Mana Font: Increases your Mana Regen by 1% per 1% Mana you are missing.", "Unique Active: Removes all stuns, roots, taunts, fears, silences, and slows on an allied champion and heals for 150 + 10% of the target’s maximum health. (180 second cooldown).", null, null, null, "Defense > Magic Resist \nMagic > Mana Regen", "1600g (720g)", "1120g");
		itemsArray[50] = new items("Morellonomicon", "http://img1.wikia.nocookie.net/__cb20131123191200/leagueoflegends/images/7/7b/Morellonomicon_item.png", "Common", "Legendary", "+75 ability power \n+12 mana regeneration \n+20% cooldown reduction", "Unique: Dealing magic damage to an enemy champion below 40% health inflicts Grievous Wounds to them for 4 seconds.", null, null, null, null, "Magic > Ability Power \nMagic > Cooldown Reduction \nMagic > Mana Regen", "2200g (765g)", "1540g");
		itemsArray[51] = new items("Nashor’s Tooth", "http://img4.wikia.nocookie.net/__cb20130616211315/leagueoflegends/images/1/16/Nashor%27s_Tooth_item.png", "Common", "Legendary", "+50% attack speed \n+60 ability power", "Unique: +20% cooldown reduction", "Unique: Basic attacks deal 15 (+ 15% AP) bonus magic damage on hit", null, null, null, "Attack > Attack Speed \nMagic > Ability Power \nMagic > Cooldown Reduction", "2920g (850g)", "2044g");
		itemsArray[52] = new items("Phantom Dancer", "http://img2.wikia.nocookie.net/__cb20130319091131/leagueoflegends/images/c/ce/Phantom_Dancer_item.png", "Common", "Legendary", "+50% attack speed \n+30% critical strike chance \n+5% movement speed", "Unique: Your champion ignores unit collision", null, null, null, null, "Attack > Attack Speed \nAttack > Critical Strike \nMovement > Other Movement Items", "2800g (495g)", "1960g");
		itemsArray[53] = new items("Randuin’s Omen", "http://img2.wikia.nocookie.net/__cb20130319091251/leagueoflegends/images/0/08/Randuin%27s_Omen_item.png", "Common", "Legendary", "+500 health \n+70 armor", "Unique Passive – Cold Steel: When hit by basic attacks, reduces the attacker’s attack speed by 15% and movement speed by 10% for 1 second.", "Unique Active: Slows the movement speed of nearby enemy units by 35% for 2 (+ 0.5% armor) (+ 0.5% magic resistance) seconds. 60 second cooldown (500 range).", null, null, null, "Defense > Armor \nDefense > Health", "3000g (1000g)", "2170g");
		itemsArray[54] = new items("Ravenous Hydra", "http://img1.wikia.nocookie.net/__cb20130710102446/leagueoflegends/images/e/e8/Ravenous_Hydra_item.png", "Common", "Legendary", "+75 attack damage \n+15 health regeneration \n+12% life steal", "Melee only.", "Passive: Damage dealt by this item benefits from life steal.", "Unique Passive – Cleave: Your attacks deal up to 60% of your Attack Damage to units around your target as physical damage (185 range), decaying down to 20% near the edge (385 range).", "Unique Active – Crescent: Deals up to 100% of your Attack Damage to units around you as physical damage, decaying down to 60% near the edge. 10 second cooldown (400 range).", null, "Attack > Attack Damage \nAttack > Life Steal \n Defense > Health Regeneration", "3300g (600g)", "2310g");
		itemsArray[55] = new items("Rod of Ages", "http://img4.wikia.nocookie.net/__cb20130319091336/leagueoflegends/images/8/8c/Rod_of_Ages_item.png", "Common", "Legendary", "+450 health \n+450 mana \n+60 ability power", "Passive: This item gains 20 health, 20 mana, and 2 ability power every minute, up to 10 times.", "Unique Passive – Valor’s Reward: On leveling up, restores 150 health and 200 mana over 8 seconds.", null, null, null, "Defense > Health \nMagic > Ability Power \nMagic > Mana", "2800g (740g)", "1960g");
		itemsArray[56] = new items("Spirit Visage", "http://img1.wikia.nocookie.net/__cb20130319091526/leagueoflegends/images/6/6f/Spirit_Visage_item.png", "Common", "Legendary", "+400 health \n+55 magic resistance \n+10% cooldown reduction \n+20 health regen", "Unique: Increases your self-healing, health regen, life steal and spell vamp by 20%", null, null, null, null, "Defense > Health \nDefense > Magic Resist \nMagic > Cooldown Reduction", "2750g (500g)", "1925g");
		itemsArray[57] = new items("Statikk Shiv", "http://img4.wikia.nocookie.net/__cb20130710102757/leagueoflegends/images/f/f8/Statikk_Shiv_item.png", "Common", "Legendary", "+40% attack speed \n+20% critical strike chance \n+6% movement speed", "Unique Passive: Moving and attacking builds Static Charges. At 100 charges, your next attack expends the charges to deal 100 magic damage to up to 4 targets. This damage can critically strike.", null, null, null, null, "Attack > Critical Strike \nAttack > Attack Speed \nMovement > Other Movement Items", "2500g (525g)", "1750g");
		itemsArray[58] = new items("Twin Shadows", "http://img1.wikia.nocookie.net/__cb20130710102449/leagueoflegends/images/4/4b/Twin_Shadows_item.png", "Common", "Legendary", "+80 ability power \n+10% cooldown reduction \n+6% movement speed", "Unique Active - Hunt: Summons 2 invulnerable ghosts for 6 seconds to seek the two nearest enemy champions. If they touch an enemy champion, they slow their movement speed by 40% and reveal them for 2.5 seconds. Ghosts that fail to find a target return to the wielder, reducing the item's cooldown by 40 seconds each. 120 second cooldown.", null, null, null, null, "Magic > Ability Power \nMagic > Cooldown Reduction \nMovement > Other Movement Items", "2400g (630g)", "1680g");
		itemsArray[59] = new items("Will of the Ancients", "http://img4.wikia.nocookie.net/__cb20130319091645/leagueoflegends/images/6/6f/Will_of_the_Ancients_item.png", "Common", "Legendary", "+80 ability power \n+10% cooldown reduction", "Unique: +20% spell vamp", null, null, null, null, "Magic > Ability Power \nMagic > Cooldown Reduction", "2500g (440g)", "1400g");
		itemsArray[60] = new items("Youmuu's Ghostblade", "http://img1.wikia.nocookie.net/__cb20131123185815/leagueoflegends/images/4/41/Youmuu%27s_Ghostblade_item.png", "Common", "Legendary", "+30 attack damage \n+15% critical strike chance \n+10% cooldown reduction", "Unique: +20 armor penetration", "Unique Active: Gain +40% attack speed and +20% movement speed for 6 seconds. 45 second cooldown", null, null, null, "Attack > Attack Speed \nAttack > Critical Strike \nAttack > Damage \nMagic > Cooldown Reduction \nMovement > Other Movement Items", "2700g (563g)", "1890g");
		itemsArray[61] = new items("Zeke's Herald", "http://img4.wikia.nocookie.net/__cb20130319091845/leagueoflegends/images/5/54/Zeke%27s_Herald_item.png", "Common", "Legendary", "+250 health \n+20% cooldown reduction", "Unique Aura: Nearby allied champions gain +20 attack damage and +10% life steal. (1100 range).", null, null, null, null, "Attack > Damage \nAttack > Life Steal \nDefense > Health \nMagic > Cooldown Reduction", "2550g (900g)", "1785g");
		itemsArray[62] = new items("Zephyr", "http://img3.wikia.nocookie.net/__cb20130710101719/leagueoflegends/images/1/11/Zephyr_item.png", "Summoner's Rift", "Legendary", "+25 attack damage \n+50% attack speed \n+10% movement speed \n+10% cooldown reduction", "Unique Passive - Tenacity: The duration of stuns, slows, taunts, fears, silences, blinds, polymorphs, and immobilizes are reduced by 35%.", null, null, null, null, "Attack > Damage \nAttack > Attack Speed \nMagic > Cooldown Reduction \nMovement > Other Movement Items", "2850g (725g)", "1995g");
		itemsArray[63] = new items("Feral Flare", "http://img1.wikia.nocookie.net/__cb20140301100532/leagueoflegends/images/7/74/Feral_Flare_item.png", "Summoner's Rift", "Mythical", "+35% attack speed \n+15 attack damage", "Unique Passive - Maim: Champion kills, assists and large monsters slain will grant Feral stacks. Basic attacks deal 100 (+3 per Feral stack) bonus magic damage and restore 10 (+1 per Feral stack) health. Enemy champions take 33% of the bonus magic damage.", "Unique: Gain 30% increased gold from monsters. You may only be in possession of 1 Gold Income item.", "Unique Active: Places a Stealth Ward at target location that lasts for 180 seconds. 180 second cooldown. (1000 cast range).", null, null, "Attack > Attack Speed \nAttack > Attack Damage", "1650g (This item cannot be bought)", "720g");
		itemsArray[64] = new items("Blade of the Ruined King", "http://img2.wikia.nocookie.net/__cb20130116010243/leagueoflegends/images/2/2f/Blade_of_the_Ruined_King_item.png", "Common", "Mythical", "+25 attack damage \n+15% life steal \n+40% attack speed", "Unique Passive: Your attacks deal 5% of the target's current health in physical damage (60 max vs minions and monsters).", "Unique Active: Drains target champion, dealing 15% of the champion's maximum health in physical damage (min. 100) and healing you for the damage dealt. Additionally you steal 30% of their movement speed for 3 seconds. 90 second cooldown. (450 range)", null, null, null, "Attack > Attack Damage \nAttack > Attack Speed \nAttack > Life Steal", "3200g (1000g)", "1995");
		itemsArray[65] = new items("Hextech Gunblade", "http://img2.wikia.nocookie.net/__cb20130319090435/leagueoflegends/images/6/64/Hextech_Gunblade_item.png", "Common", "Mythical", "+45 attack damage \n+65 ability power \n+12% life steal", "Unique Passive: +20% spell vamp", "Unique Passive - Reload: Your basic attacks and single target spells against champions reduce the cooldown of this item by 3 seconds.", "Unique Active: Deals 150 (+ 40% AP) magic damage and slow sthe target champion's movement speed by 40% for 2 seconds. 60 second cooldown. (700 range)", null, null, "Attack > Damage \nAttack > Life Steal \nMagic > Ability Power", "3400g (800g)", "2380g");
		itemsArray[66] = new items("Muramana", "http://img1.wikia.nocookie.net/__cb20130710101717/leagueoflegends/images/1/18/Muramana_item.png", "Common", "Mythical", "+1000 mana \n+20 attack damage \n+7 mana regeneration", "Unique Passive - Awe: Gain attack damage equal to 2% of your maximum mana.", "Toggle Active: Single target spells and attacks (on hit) consume 3% of current mana to deal bonus physical damage equal to twice the amount of Mana consumed.", null, null, null, "N/A", "2100g (This item cannot be bought)", "1897g");
		itemsArray[67] = new items("Seraph's Embrace", "http://img2.wikia.nocookie.net/__cb20130710101718/leagueoflegends/images/b/b9/Seraph%27s_Embrace_item.png", "Common", "Mythical", "+1000 mana \n+60 ability power \n+10 mana regeneration", "Unique Passive - Insight: Gain ability power equal to 3% of your maximum mana.", "Unique Active - Mana Shield: Drains 20% of your current mana to shield yourself for an equal amount plus 150 for 3 seconds (120 second cooldown)", null, null, null, "N/A", "2700g (This item cannot be bought)", "1897g");
		//itemsArray[68] = new items("")
		//itemsArray[69] = new items("")
		//itemsArray[70] = new items("")


		



		
		
	}
	
	public static void main(String[] args) {
		
		
		itemsArray[0] = new items("Boots of Speed", "http://img1.wikia.nocookie.net/__cb20130319090217/leagueoflegends/images/4/4e/Boots_of_Speed_item.png", "Common", "Basic", null, "Unique - Enhanced Movement: +25 movement speed", null, null, null, null, "Movement", "325g", "227g");
		itemsArray[1] = new items("Berserker's Greaves", "http://img4.wikia.nocookie.net/__cb20130116005955/leagueoflegends/images/b/bd/Berserker%27s_Greaves_item.png", "Common", "Advanced", "+20% atttack speed", "Unique - Enhanced Movement: +45 movement speed", null, null, null, null, "Attack > Attack Speed \nMovement", "900g (175g)", "630g");
		itemsArray[2] = new items("Boots of Mobility", "http://img2.wikia.nocookie.net/__cb20130319090211/leagueoflegends/images/9/90/Boots_of_Mobility_item.png", "Common", "Advanced", null, "Unique - Enhanced Movement: +25 movement speed. Increases to +105 movement speed when out of combat for 5 seconds.", null, null, null, null, "Movement", "800g (475g)", "560g");
		itemsArray[3] = new items("Boots of Swiftness", "http://img2.wikia.nocookie.net/__cb20130319090224/leagueoflegends/images/6/69/Boots_of_Swiftness_item.png", "Common", "Advanced", null, "Unique - Enhanced Movement: +60 movement speed.", "Unique - Slow Resist: Movement slowing effects are reduced by 25%", null, null, null, "Movement", "1000g (675g)", "700g");
		itemsArray[4] = new items("Mercury's Treads", "http://img1.wikia.nocookie.net/__cb20130319090758/leagueoflegends/images/9/96/Mercury%27s_Treads_item.png", "Common", "Advanced", "+25 magic resistance", "Unique - Enhanced Movement: +45 movement speed", "Unique - Tenacity: the duration of stuns, slows, taunts, fears, silences, blinds, and immobilizes are reduced by 35%.", null, null, null, "Defense > Magic Resist \nMovement", "1200g (475g)", "840g");
		itemsArray[5] = new items("Ninja Tabi", "http://img2.wikia.nocookie.net/__cb20130319091031/leagueoflegends/images/3/35/Ninja_Tabi_item.png", "Common", "Advanced", "+25 armor", "Unique - Enhanced Movement: +45 movement speed.", "Unique: Blocks 10% of the damage from basic attacks.", null, null, null, "Defense > Armor \nMovement", "1000g (375g)", "700g");
		itemsArray[6] = new items("Sorcerer's Shoes", "http://img2.wikia.nocookie.net/__cb20130319091505/leagueoflegends/images/6/60/Sorcerer%27s_Shoes_item.png", "Common", "Advanced", "+15 magic penetration", "Unique - Enhanced Movement: +45 movement speed.", null, null, null, null, "Movement", "1100g (775g)", "770g");

		
		
		System.out.println("done creating items");
	}


}